name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r counterpoint_gen/requirements.txt
      - name: Run tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=. pytest

  go-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v4
      - name: Install PortMidi and ALSA dev headers
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libportmidi-dev
      - name: Run Go tests
        run: |
          for d in */; do
            cd "$d"
            go test ./...
            cd ..
          done

  node-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node/midi-live-tools
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm test